def utils
def backendPipeline

pipeline {

    agent {
        docker {
            image 'docker-registry-internal-release.netcetera.com/nca-341-2/toolbox:1.1.3-openjdk21'
            args '-v /var/run/docker.sock:/var/run/docker.sock'
            alwaysPull true
            label 'docker'
        }
    }

    environment {
        BITBUCKET_USER = credentials('11d1c8ab-bef2-4ed4-b79d-eb8d3db3d9f2')
        IS_RELEASE = "${params.RELEASE_BUILD}"
        RELEASE_VERSION = "${params.RELEASE_VERSION}"
        DEVELOPMENT_VERSION = "${params.DEVELOPMENT_VERSION}"
    }

    parameters {
        booleanParam(name: 'RELEASE_BUILD', defaultValue: false, description: 'Trigger a release build')
        string(name: 'RELEASE_VERSION', defaultValue: '', description: 'Version number for the release')
        string(name: 'DEVELOPMENT_VERSION', defaultValue: '',
                description: 'Version number for the development stream after the release')
    }

    stages {

        stage('Pre Flight') {
            steps {
                script {
                    // Load scripts
                    utils = load 'jenkins/pipelines/shared/utils.groovy'
                    backendPipeline = load 'jenkins/pipelines/ci/backendPipeline.groovy'

                    utils.bitbucketNotification("INPROGRESS")
                }
            }
        }

        stage('CI: Build & Test') {
            parallel {
                stage('Backend CI') {
                    steps {
                        script {
                            backendPipeline(IS_RELEASE,RELEASE_VERSION,DEVELOPMENT_VERSION)
                        }
                    }
                }
            }
        }

        stage('Testing') {
            parallel {
                stage('Integration Tests') {
                    steps {
                        script {
                            sh 'echo "Integration tests executed successfully"'
                        }
                    }
                }
                stage('UI Tests') {
                    steps {
                        script {
                            sh 'echo "UI test executed successfully"'
                        }
                    }
                }
            }
        }

        stage('CD: Deploy to Staging') {
            when {
                branch 'master'
            }
            steps {
                script {
                    sh 'echo "Deployed to Staging"'
                }
            }
        }

        stage('CD: Deploy to Production') {
            when {
                allOf {
                    branch 'master'
                    expression {
                        return IS_RELEASE
                    }
                }
            }
            steps {
                script {
                    sh 'echo "Deployed to Production"'
                }
            }
        }

    }

    post {
        always {
            script {
                utils.bitbucketNotification()
            }
        }
    }
}